### ISSUE TITLE
Group code 11th and 12th in CBSE Schools

### ISSUE THREAD

**Issue by senthilemis** [tnemis/live-server#10]
![cbse group code](https://cloud.githubusercontent.com/assets/23474552/21560476/cf2ffe70-ce85-11e6-8dff-d34eb41cd97a.png)

CBSE Schools find difficulty in entering Group code for 11th and 12th std as they don't have it. How to rectify it.

**Comment by emisteam** [comment]
this can be done by modifying the child detail form not to show group code to cbse schools. before that we should get SPD madam's approval(also should check do they have separate group codes)
