### ISSUE TITLE
Sensitive data exposure is still open

### ISSUE THREAD

**Issue by palaniappan47** [tnemis/live-server#12]
Still the live server code and staging server code having the sensitive information in commit history.
The screen shot below shows the sensitive data exposure to anonymous user.
Make sure you remove it from commit history.

![github](https://cloud.githubusercontent.com/assets/10289334/21562328/20b71f4a-ce9e-11e6-9ab4-c6796bba3779.png)

**Comment by palaniappan47** [comment]
@mageshsugu 
Also remove completely the redis caching server host ip & port number, sms gateway credentials, email back-end credentials from settings.py and clear them from commit history.

**Comment by emisteam** [comment]
Dear team members and @palaniappan47 
                                               As removing commit history alone is not going to replace commit history all the forked repos and github catch i propose to merge all the pull requests at present and create a new repo with the new code minus sensitive data please comment immediately
![commit_clean](https://cloud.githubusercontent.com/assets/23469480/21584890/0911aa1a-d0db-11e6-948f-290b19f1f41a.png)

**Comment by emisteam** [comment]
now removed the settings.py file from all history
