### ISSUE TITLE
changes in bank

### ISSUE THREAD

**Issue by emisteam** [tnemis/live-server#2]
modify the code for "bank details mandatory  only for 12 (govt and aided sections of aided schools)"

**Comment by mravikumar281** [comment]
Code corrected and sent via mail.

**Comment by emisteam** [comment]
Dear Mr.Ravi sir code committed to git repo and issue closed.

Dear Team  As for as the chaining, code already been finished but db works pending. once db work completed code can be pushed.(refer mail on 25 novemver 2016 from Mr. Magesh)
