### ISSUE TITLE
Download Child Profile -- FieldError

### ISSUE THREAD

**Issue by jenefabrando** [tnemis/live-server#20]
In the class wise list page, while clicking the Download Child Profile link, the following error is shown due to the bank chaining code.

FieldError at /students/child_detail/download_child_profile/11/
Cannot resolve keyword 'bank' into field.

So, please solve this issue.

**Comment by mageshsugu** [comment]
This problem is not with the code you have to modify your database for bank
chaining please refer our group mail for this

**Comment by thamaraiselvann** [comment]
Download Child Profile Bank  Field Error Solved...

**Comment by emisteam** [comment]
banknew field updated
