### ISSUE TITLE
Sensitive data expose

### ISSUE THREAD

**Issue by palaniappan47** [tnemis/live-server#36]
Again the settings.py file has been updated with sensitive data. Remove the DB config and os import lines from live server and history

**Comment by mageshsugu** [comment]
Can't get your point...

**Comment by palaniappan47** [comment]
@mageshsugu remove the settings.py and settings.pyc files from live server code

**Comment by mageshsugu** [comment]
@palaniappan47 there is no such file . Clear your cache and check
