### ISSUE TITLE
photo validation prevents updation in mother name field

### ISSUE THREAD

**Issue by emisteam** [tnemis/live-server#4]
even though a valid photo url is assaigned in the photo field and photo is shown,updation of mother name is prevented because against file selection button "no file selected is displayed". Changes needed in photo validation.

**Comment by rjsiva** [comment]
I have tried various mandatory option like Jquery , class=mandatory etc., but I couldn't achieve the result.So, I left with an option, calling that javascript in mother name field ,as its only allow after upload the photo .The same is happening in edit (Also got a idea of writing seperate mother name field without that script in update, but its not seems to be perfect).If you have any suggestion in rising mandatory for update kindly post it.

**Comment by thamaraiselvann** [comment]
​
The mother name field ​not editable  issue has been carried out...
Some additional changes are made ​in ​photo field.
1.while creating the selected photo is displayed as thumbnail.
2.while updating both existing photo and newly chosen photos are displayed.
3.photo field made mandatory for all classes (may be it can be modified if required)

**Comment by rjsiva** [comment]
Thanks for the updation. Its seems class= mandatory is working fine.Just made the two scripts under single validate_photo script.Also removed the old photo in the child_detail_views.py when the new photo is get updated (Which is not done for so long as old photos are accumulating in the server).Can be tested and merged if it solves all the issues.

**Comment by emisteam** [comment]
Team members pls comment

**Comment by thamaraiselvann** [comment]
The Photo Validation issue has been carried out..Both Scripts are separately working properly.So no need to combine the two.Existing photo removing issue also solved.
**Some additional changes are made ​in ​photo field**.
1.Removed Clear  Check box Near photo Field.
2.while creating the selected photo is displayed as thumbnail.
3.while updating both existing photo and newly chosen photos are displayed.
4.photo field made mandatory for all classes (may be it can be modified if required)

**Comment by emisteam** [comment]
CODE CORRECTED IN ANOTHER PR
